const data = [
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Cộng hòa xã hội chủ nghĩa việt nam độc lập tự do hạnh phúc',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam', 'độc lập'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: [
      'cộng hòa',
      'xã hội',
      'chủ nghĩa',
      'việt nam',
      'độc lập',
      'tự do',
      'hạnh phúc',
      'tôi',
      'nói',
      'đồng bào',
      'có nghe',
      'rõ không',
      'hả',
      'nếu không',
      'nghe',
      'rõ',
    ],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
  {
    avatar: 'https://bulma.io/images/placeholders/128x128.png',
    author: 'Nguyễn Roãn Tú',
    date: '13 tháng 9 năm 2019',
    title: 'Có mắt như mù',
    tags: ['cộng hòa', 'xã hội', 'chủ nghĩa', 'việt nam'],
    views: 12,
    clips: 25,
    comments: 153,
    posts: 12,
    claps: 1563,
  },
]

export default data
