export { default as EditArticle } from './EditArticle.vue'
export { default as EditCategory } from './EditCategory.vue'
export { default as EditTag } from './EditTag.vue'
export { default as EditUser } from './EditUser.vue'
export { default as EditOrganization } from './EditOrganization.vue'
export { default as EditRole } from './EditRole.vue'
export { default as EditFeedback } from './EditFeedback.vue'
